### ISSUE TITLE
Import medicine classifier

### ISSUE THREAD

**Issue by Glamdring** [Da-Bulgaria/e-prescriptions#7]
Select and import a list of medicines from official sources

https://portal.ncpr.bg/registers/

In addition to this list (to be stored in the database), we also need to include a list of all non-proprietary names. It should be stored separately, as it lacks many properties of the positive list (it's just a list of strings). It can be taken from here https://github.com/jperales/vulcanspot/blob/37c6b45ca233cd737c39e41396b987762faa1a5f/data/Annotation/PD_table.tsv

It should be parsed to produce a simple list. The 2nd column should be added as a new item only if it differs from the common_name (for example: paracetamol and acetaminophen)

Also consider: ftp://ftp.cdc.gov/pub/Health_Statistics/NCHS/Publications/ICD10CM/2020/icd10cm_drug_2020.xml

**Comment by hovanessyan** [comment]
Which are the official sources?
